/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface QuizNavBar {
    }
}
declare global {
    interface HTMLQuizNavBarElement extends Components.QuizNavBar, HTMLStencilElement {
    }
    var HTMLQuizNavBarElement: {
        prototype: HTMLQuizNavBarElement;
        new (): HTMLQuizNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "quiz-nav-bar": HTMLQuizNavBarElement;
    }
}
declare namespace LocalJSX {
    interface QuizNavBar {
    }
    interface IntrinsicElements {
        "quiz-nav-bar": QuizNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "quiz-nav-bar": LocalJSX.QuizNavBar & JSXBase.HTMLAttributes<HTMLQuizNavBarElement>;
        }
    }
}
